-- MySQL Script generated by MySQL Workbench
-- Mon Nov 27 14:46:03 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema warehouse
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema warehouse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `warehouse` DEFAULT CHARACTER SET utf8 ;
USE `warehouse` ;

-- -----------------------------------------------------
-- Table `warehouse`.`quadrants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `warehouse`.`quadrants` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `total_space` INT NULL,
  `free_space` INT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `warehouse`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `warehouse`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quadrant_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `quantity` INT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `productscol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_quadrants_idx` (`quadrant_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_quadrants`
    FOREIGN KEY (`quadrant_id`)
    REFERENCES `warehouse`.`quadrants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
